#!/usr/bin/env bash
set -eu

VERSION="${SLSSTEAM_VERSION:-}"
COMMIT="${SLSSTEAM_COMMIT:-}"

if [ -z "$VERSION" ]; then
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		VERSION="$(git log -1 --format=%cd --date=format:%Y%m%d%H%M%S)"
	else
		VERSION="$(date -u '+%Y%m%d%H%M%S')"
	fi
fi

if [ -z "$COMMIT" ]; then
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
		COMMIT="$(git rev-parse --short=12 HEAD)"
	else
		COMMIT="unknown"
	fi
fi

case "$VERSION" in
	*[!0-9]*|'')
		echo "embed-version.sh: SLSSTEAM_VERSION must be numeric, got '$VERSION'" >&2
		exit 1
		;;
esac

case "$COMMIT" in
	*[!A-Za-z0-9._-]*|'')
		echo "embed-version.sh: SLSSTEAM_COMMIT must be alphanumeric plus ._- only, got '$COMMIT'" >&2
		exit 1
		;;
esac

mkdir -p src
tmp="$(mktemp)"
cat > "$tmp" <<EOF
#pragma once

#include <cstdint>

// Generated by embed-version.sh. Do not edit by hand.
constexpr uint64_t VERSION = $VERSION;
constexpr const char* COMMIT_HASH = "$COMMIT";
EOF

if [ ! -f src/version.gen.hpp ] || ! cmp -s "$tmp" src/version.gen.hpp; then
	mv "$tmp" src/version.gen.hpp
else
	rm "$tmp"
fi
